### ISSUE TITLE
Can't install on ubuntu 18 x64

### ISSUE THREAD

**Issue by tuanha2000vn** [ohollo/chord-extractor#2]
Hi there, I've tried this on windows and it work perfect.

However as I tried to install on Ubuntu 18 there's an issue with "Failed building wheel for llvmlite"

Could you please help fix it. Thank.

```
tuanha@tuanha-MS-7918:~$ pip3 install chord_extractor
Collecting chord_extractor
  Using cached https://files.pythonhosted.org/packages/18/fe/d87737db490da2c13f23cd7120db3ee8aa27a32c465ded3903e733a5fc8c/chord_extractor-0.1.2-py3-none-any.whl
Collecting vamp (from chord_extractor)
Collecting librosa (from chord_extractor)
  Using cached https://files.pythonhosted.org/packages/e4/1c/23ef2fd02913d65d43dc7516fc829af709314a66c6f0bdc2e361fdcecc2d/librosa-0.9.2-py3-none-any.whl
Collecting decorator>=4.0.10 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
Collecting packaging>=20.0 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl
Collecting scikit-learn>=0.19.1 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/f5/ef/bcd79e8d59250d6e8478eb1290dc6e05be42b3be8a86e3954146adbc171a/scikit_learn-0.24.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting soundfile>=0.10.2 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/e3/ba/42a4370e4fb84fd8956dabf115a0b7f0f3071400a52554526fe5fd32f275/soundfile-0.11.0-py2.py3-none-any.whl
Collecting resampy>=0.2.2 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/f2/d3/5209fd2132452f199b1ddf0d084f9fd5f5f910840e3b282f005b48a503e1/resampy-0.4.2-py3-none-any.whl
Collecting joblib>=0.14 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/7c/91/d3ba0401e62d7e42816bc7d97b82d19c95c164b3e149a87c0a1c026a735e/joblib-1.1.1-py2.py3-none-any.whl
Collecting pooch>=1.0 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/8d/64/8e1bfeda3ba0f267b2d9a918e8ca51db8652d0e1a3412a5b3dbce85d90b6/pooch-1.6.0-py3-none-any.whl
Collecting audioread>=2.1.9 (from librosa->chord_extractor)
Collecting numba>=0.45.1 (from librosa->chord_extractor)
Collecting numpy>=1.17.0 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=1.2.0 (from librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging>=20.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.19.1->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/61/cf/6e354304bcb9c6413c4e02a747b600061c21d38ba51e7e544ac7bc66aecc/threadpoolctl-3.1.0-py3-none-any.whl
Collecting cffi>=1.0 (from soundfile>=0.10.2->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/3a/12/d6066828014b9ccb2bbb8e1d9dc28872d20669b65aeb4a86806a0757813f/cffi-1.15.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Collecting requests>=2.19.0 (from pooch>=1.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl
Collecting appdirs>=1.3.0 (from pooch>=1.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting llvmlite<0.37,>=0.36.0rc1 (from numba>=0.45.1->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/19/66/6b2c49c7c68da48d17059882fdb9ad9ac9e5ac3f22b00874d7996e3c44a8/llvmlite-0.36.0.tar.gz
Collecting setuptools (from numba>=0.45.1->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/b0/3a/88b210db68e56854d0bcf4b38e165e03be377e13907746f825790f3df5bf/setuptools-59.6.0-py3-none-any.whl
Collecting pycparser (from cffi>=1.0->soundfile>=0.10.2->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3" (from requests>=2.19.0->pooch>=1.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests>=2.19.0->pooch>=1.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/fe/ca/466766e20b767ddb9b951202542310cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl
Collecting charset-normalizer~=2.0.0; python_version >= "3" (from requests>=2.19.0->pooch>=1.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/06/b3/24afc8868eba069a7f03650ac750a778862dc34941a4bebeb58706715726/charset_normalizer-2.0.12-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.19.0->pooch>=1.0->librosa->chord_extractor)
  Using cached https://files.pythonhosted.org/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-covvbir1/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbuxhprdcpip-wheel- --python-tag cp36:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-build-covvbir1/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-build-covvbir1/llvmlite/ffi/build.py", line 220, in <module>
      main()
    File "/tmp/pip-build-covvbir1/llvmlite/ffi/build.py", line 210, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-covvbir1/llvmlite/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python3' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: vamp, decorator, pyparsing, packaging, threadpoolctl, numpy, scipy, joblib, scikit-learn, pycparser, cffi, soundfile, llvmlite, setuptools, numba, resampy, idna, urllib3, charset-normalizer, certifi, requests, appdirs, pooch, audioread, librosa, chord-extractor
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-covvbir1/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-leq86ucp-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    /home/tuanha/.local/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    got version from file /tmp/pip-build-covvbir1/llvmlite/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-covvbir1/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-covvbir1/llvmlite/ffi/build.py", line 220, in <module>
        main()
      File "/tmp/pip-build-covvbir1/llvmlite/ffi/build.py", line 210, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-covvbir1/llvmlite/ffi/build.py", line 134, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-covvbir1/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-leq86ucp-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-covvbir1/llvmlite/
tuanha@tuanha-MS-7918:~$ 
```

**Comment by ohollo** [comment]
Hi, please confirm what Python version you're using and that you followed the prerequisite instructions in the readme before running "pip install chord-extractor".

Please also try running an update of pip before installation.

**Comment by tuanha2000vn** [comment]
Thank for answering

I've managed to install chord-extractor to Ubuntu 22 in Python 3.8.9, no error found 
```
(env) tuanha@tuanha-MS-7918:~/Documents/python/chord_sense_python$ pip install chord-extractor
Requirement already satisfied: chord-extractor in ./env/lib/python3.8/site-packages (0.1.2)
Requirement already satisfied: librosa in ./env/lib/python3.8/site-packages (from chord-extractor) (0.9.2)
Requirement already satisfied: vamp in ./env/lib/python3.8/site-packages (from chord-extractor) (1.1.0)
Requirement already satisfied: soundfile>=0.10.2 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (3.0.0)
Requirement already satisfied: resampy>=0.2.2 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (0.4.2)
Requirement already satisfied: numpy>=1.17.0 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (1.23.5)
Requirement already satisfied: scipy>=1.2.0 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (1.10.0)
Requirement already satisfied: numba>=0.45.1 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (0.56.4)
Requirement already satisfied: packaging>=20.0 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (23.0)
Requirement already satisfied: decorator>=4.0.10 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (5.1.1)
Requirement already satisfied: scikit-learn>=0.19.1 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (1.2.1)
Requirement already satisfied: joblib>=0.14 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (1.2.0)
Requirement already satisfied: pooch>=1.0 in ./env/lib/python3.8/site-packages (from librosa->chord-extractor) (1.6.0)
Requirement already satisfied: setuptools in ./env/lib/python3.8/site-packages (from numba>=0.45.1->librosa->chord-extractor) (67.1.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in ./env/lib/python3.8/site-packages (from numba>=0.45.1->librosa->chord-extractor) (0.39.1)
Requirement already satisfied: importlib-metadata in ./env/lib/python3.8/site-packages (from numba>=0.45.1->librosa->chord-extractor) (6.0.0)
Requirement already satisfied: appdirs>=1.3.0 in ./env/lib/python3.8/site-packages (from pooch>=1.0->librosa->chord-extractor) (1.4.4)
Requirement already satisfied: requests>=2.19.0 in ./env/lib/python3.8/site-packages (from pooch>=1.0->librosa->chord-extractor) (2.28.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./env/lib/python3.8/site-packages (from scikit-learn>=0.19.1->librosa->chord-extractor) (3.1.0)
Requirement already satisfied: cffi>=1.0 in ./env/lib/python3.8/site-packages (from soundfile>=0.10.2->librosa->chord-extractor) (1.15.1)
Requirement already satisfied: pycparser in ./env/lib/python3.8/site-packages (from cffi>=1.0->soundfile>=0.10.2->librosa->chord-extractor) (2.21)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.8/site-packages (from requests>=2.19.0->pooch>=1.0->librosa->chord-extractor) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.8/site-packages (from requests>=2.19.0->pooch>=1.0->librosa->chord-extractor) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in ./env/lib/python3.8/site-packages (from requests>=2.19.0->pooch>=1.0->librosa->chord-extractor) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.8/site-packages (from requests>=2.19.0->pooch>=1.0->librosa->chord-extractor) (2022.12.7)
Requirement already satisfied: zipp>=0.5 in ./env/lib/python3.8/site-packages (from importlib-metadata->numba>=0.45.1->librosa->chord-extractor) (3.12.1)
```

But I still got error running a simple test file

```
from chord_extractor.extractors import Chordino

chordino = Chordino(roll_on=1)
file_path = f'mp3download/0Y6DsQvk89k.mp3'
chords = chordino.extract(file_path)
```
This is the error ModuleNotFoundError: No module named 'chord_extractor'" error message on a simple test file
```
(env) tuanha@tuanha-MS-7918:~/Documents/python/chord_sense_python$ /bin/python3 /home/tuanha/Documents/python/chord_sense_python/main.py
Traceback (most recent call last):
  File "/home/tuanha/Documents/python/chord_sense_python/main.py", line 1, in <module>
    from chord_extractor.extractors import Chordino
ModuleNotFoundError: No module named 'chord_extractor'
```
Please help. Thank you.

**Comment by ohollo** [comment]
It's hard to tell whether this is a genuine issue with the library that I need to fix, or just a quirk in your environment, which I'm not in a position to troubleshoot. There is a Dockerfile in the repository. You can try building that and if it builds properly (which it should), run off of that image, or see why it ran fine there and not in your current environment.

**Comment by ohollo** [comment]
Closing the issue shortly as am assuming this is not relating to a bug.

**Comment by tuanha2000vn** [comment]
Thank, I found the issue only relate to Mac M1 CPU, I think it's not supported.
